In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, classification_report, confusion_matrix

In [2]:
data = pd.read_csv("shop_smart_ecommerce.csv")
data.sample(5)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
5935,1,129.0,1,26.70,28,1392.100000,0.031111,0.056333,0.000000,0.0,Sep,3,2,7,13,Returning_Visitor,True,False
11682,6,213.5,0,0.00,11,303.500000,0.000000,0.016667,87.902961,0.0,Dec,8,13,9,20,Other,False,True
11399,4,54.5,0,0.00,74,1599.994589,0.000000,0.002632,67.266161,0.0,Dec,2,4,6,2,Returning_Visitor,False,True
8306,4,159.0,2,27.75,33,821.682540,0.000617,0.019343,0.000000,0.0,Dec,2,2,1,2,Returning_Visitor,False,True
6394,3,145.2,0,0.00,28,425.096905,0.000000,0.002381,0.000000,0.0,Oct,3,2,7,11,New_Visitor,True,False

In [3]:
data["VisitorType"].value_counts()

VisitorType
Returning_Visitor    10551
New_Visitor           1694
Other                   85
Name: count, dtype: int64

In [4]:
data["Product_Page_Duration"] = data["ProductRelated"]*data["ProductRelated_Duration"]

In [5]:
data

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue,Product_Page_Duration
0,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,1,1,1,1,Returning_Visitor,False,False,0.000000
1,0,0.0,0,0.0,2,64.000000,0.000000,0.100000,0.000000,0.0,Feb,2,2,1,2,Returning_Visitor,False,False,128.000000
2,0,0.0,0,0.0,1,0.000000,0.200000,0.200000,0.000000,0.0,Feb,4,1,9,3,Returning_Visitor,False,False,0.000000
3,0,0.0,0,0.0,2,2.666667,0.050000,0.140000,0.000000,0.0,Feb,3,2,2,4,Returning_Visitor,False,False,5.333333
4,0,0.0,0,0.0,10,627.500000,0.020000,0.050000,0.000000,0.0,Feb,3,3,1,4,Returning_Visitor,True,False,6275.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12325,3,145.0,0,0.0,53,1783.791667,0.007143,0.029031,12.241717,0.0,Dec,4,6,1,1,Returning_Visitor,True,False,94540.958351
12326,0,0.0,0,0.0,5,465.750000,0.000000,0.021333,0.000000,0.0,Nov,3,2,1,8,Returning_Visitor,True,False,2328.750000
12327,0,0.0,0,0.0,6,184.250000,0.083333,0.086667,0.000000,0.0,Nov,3,2,1,13,Returning_Visitor,True,False,1105.500000
12328,4,75.0,0,0.0,15,346.000000,0.000000,0.021053,0.000000,0.0,Nov,2,2,3,11,Returning_Visitor,False,False,5190.000000
12329,0,0.0,0,0.0,3,21.250000,0.000000,0.066667,0.000000,0.0,Nov,3,2,1,2,New_Visitor,True,False,63.750000

In [6]:
data["Revenue"].value_counts()

Revenue
False    10422
True      1908
Name: count, dtype: int64

In [7]:
x = data.drop("Revenue",axis = 1)
y = data["Revenue"].map({True:1,False:0})

In [8]:
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
12325    0
12326    0
12327    0
12328    0
12329    0
Name: Revenue, Length: 12330, dtype: int64

In [9]:
num = x.select_dtypes(include=["int64","float64"]).columns
cat = x.select_dtypes(include=["object","category"]).columns

In [10]:
print(cat)
print(num)

Index(['Month', 'VisitorType'], dtype='object')
Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType',
       'Product_Page_Duration'],
      dtype='object')

In [11]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),num),
        ("cat",OneHotEncoder(),cat)
    ]
)

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

In [13]:
tree = DecisionTreeClassifier(random_state = 42)

path = tree.cost_complexity_pruning_path(preprocessor.fit_transform(x_train),y_train)
alphas = path.ccp_alphas
print(alphas)

[0.00000000e+00 5.72724113e-05 6.23869237e-05 6.50826550e-05
 6.55980154e-05 6.60140704e-05 6.67999522e-05 6.69166673e-05
 6.70578197e-05 6.72124316e-05 6.73435909e-05 6.74602098e-05
 8.00358561e-05 8.11030008e-05 8.11030008e-05 8.29462508e-05
 8.44822925e-05 8.68960723e-05 8.87064071e-05 8.87064071e-05
 8.87064071e-05 8.87064071e-05 8.87064071e-05 8.94317602e-05
 8.96812028e-05 9.07982102e-05 9.21625009e-05 9.21625009e-05
 9.29305218e-05 9.29305218e-05 9.35803856e-05 9.35803856e-05
 9.35803856e-05 9.38692139e-05 9.50425791e-05 9.50425791e-05
 9.54152951e-05 9.54152951e-05 9.54152951e-05 9.57465982e-05
 9.57465982e-05 9.60178457e-05 9.60430273e-05 9.60430273e-05
 9.63098135e-05 9.63098135e-05 9.65511914e-05 9.67706260e-05
 9.72408428e-05 9.74795683e-05 9.76239825e-05 9.78829320e-05
 9.79994593e-05 9.79994593e-05 9.80012253e-05 9.81084687e-05
 9.83066676e-05 9.83525196e-05 9.85850319e-05 9.87088721e-05
 9.87108891e-05 9.88442822e-05 9.89060986e-05 9.90211056e-05
 9.94291596e-05 1.00008768e-04 1.00226720e-04 1.00362531e-04
 1.00841251e-04 1.01042798e-04 1.01378751e-04 1.01378751e-04
 1.01378751e-04 1.01378751e-04 1.01378751e-04 1.02529330e-04
 1.02643727e-04 1.14677963e-04 1.17377216e-04 1.18275210e-04
 1.19269119e-04 1.20152594e-04 1.20688989e-04 1.21654501e-04
 1.23341659e-04 1.23907362e-04 1.25158952e-04 1.26723439e-04
 1.26723439e-04 1.30165310e-04 1.31931888e-04 1.32167853e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.35171668e-04 1.35171668e-04 1.35171668e-04
 1.35171668e-04 1.44826787e-04 1.45845937e-04 1.47460001e-04
 1.48753617e-04 1.49086399e-04 1.50289552e-04 1.51223304e-04
 1.52068127e-04 1.52068127e-04 1.52068127e-04 1.52068127e-04
 1.52068127e-04 1.52068127e-04 1.52068127e-04 1.52068127e-04
 1.52068127e-04 1.52068127e-04 1.52068127e-04 1.52068127e-04
 1.52068127e-04 1.52068127e-04 1.52068127e-04 1.52068127e-04
 1.52068127e-04 1.52068127e-04 1.52664472e-04 1.53024530e-04
 1.53604168e-04 1.54481906e-04 1.54481906e-04 1.57700279e-04
 1.57700279e-04 1.60423518e-04 1.61947323e-04 1.62206002e-04
 1.62206002e-04 1.62206002e-04 1.62206002e-04 1.62206002e-04
 1.62206002e-04 1.62206002e-04 1.62485498e-04 1.62546125e-04
 1.63226165e-04 1.63473236e-04 1.63557718e-04 1.66148509e-04
 1.66975576e-04 1.67623596e-04 1.68298715e-04 1.68964585e-04
 1.68964585e-04 1.68964585e-04 1.68964585e-04 1.68964585e-04
 1.68964585e-04 1.68964585e-04 1.68964585e-04 1.68964585e-04
 1.69827167e-04 1.70771693e-04 1.71336018e-04 1.71336018e-04
 1.71564040e-04 1.71564040e-04 1.72001276e-04 1.72804689e-04
 1.73792145e-04 1.73792145e-04 1.73792145e-04 1.73792145e-04
 1.73792145e-04 1.73792145e-04 1.73956720e-04 1.74431086e-04
 1.75723168e-04 1.76711578e-04 1.77412814e-04 1.77412814e-04
 1.77412814e-04 1.77412814e-04 1.77412814e-04 1.77412814e-04
 1.79125795e-04 1.79524872e-04 1.80067972e-04 1.80228891e-04
 1.80228891e-04 1.80228891e-04 1.80228891e-04 1.80228891e-04
 1.80228891e-04 1.81397994e-04 1.82481752e-04 1.82481752e-04
 1.82481752e-04 1.83135808e-04 1.83353827e-04 1.84325002e-04
 1.84329694e-04 1.85047845e-04 1.85861044e-04 1.88274823e-04
 1.89040293e-04 1.89240335e-04 1.90085158e-04 1.90085158e-04
 1.90929406e-04 1.91493196e-04 1.91565403e-04 1.94711569e-04
 1.95516163e-04 1.95948868e-04 1.96156656e-04 1.96391110e-04
 1.96421330e-04 1.96564908e-04 1.96594908e-04 1.98068533e-04
 1.99542406e-04 2.00331344e-04 2.00709446e-04 2.02757502e-04
 2.04447148e-04 2.06981617e-04 2.07956412e-04 2.07956412e-04
 2.08323394e-04 2.08550574e-04 2.09416522e-04 2.11181001e-04
 2.14343645e-04 2.17127077e-04 2.17757419e-04 2.18978102e-04
 2.19653961e-04 2.19752006e-04 2.21450885e-04 2.21909836e-04
 2.23033252e-04 2.28102190e-04 2.28673874e-04 2.31722859e-04
 2.33231472e-04 2.35121583e-04 2.38162802e-04 2.38710117e-04
 2.38751490e-04 2.39928191e-04 2.43309002e-04 2.44543744e-04
 2.45379717e-04 2.48377940e-04 2.48658042e-04 2.50924362e-04
 2.54892264e-04 2.57730487e-04 2.57876213e-04 2.58515815e-04
 2.64718594e-04 2.67651043e-04 2.68747419e-04 2.71550226e-04
 2.76174424e-04 2.85201931e-04 2.85499360e-04 2.85702369e-04
 2.89653574e-04 2.90530158e-04 2.93751672e-04 2.94809524e-04
 2.96567982e-04 2.97940885e-04 3.00574919e-04 3.04136253e-04
 3.04136253e-04 3.12442495e-04 3.12617613e-04 3.12825860e-04
 3.13358130e-04 3.14596855e-04 3.16812817e-04 3.19070251e-04
 3.20583086e-04 3.21268590e-04 3.21803959e-04 3.24412003e-04
 3.25574139e-04 3.27531349e-04 3.38902553e-04 3.40401584e-04
 3.55847212e-04 3.61846288e-04 3.66673313e-04 3.67320049e-04
 3.73127710e-04 3.80733532e-04 3.81344929e-04 3.86689977e-04
 4.05756382e-04 4.08878735e-04 4.27480400e-04 4.33271834e-04
 4.85026496e-04 5.06250080e-04 5.37556531e-04 5.61332385e-04
 6.14689720e-04 6.40149330e-04 7.42489055e-04 8.32401635e-04
 1.10975936e-03 1.37708013e-03 1.90601342e-03 2.32720179e-03
 2.55182630e-03 3.41064638e-03 3.65950993e-03 1.01473548e-02
 9.36090799e-02]

In [14]:
# Grid Search CV :

from sklearn.model_selection import GridSearchCV

model = DecisionTreeClassifier(random_state=42)

pipe = Pipeline(
    steps=[
        ("preprocess", preprocessor),
        ("model", model)
    ]
)

param_grid = {
    "model__ccp_alpha" : [0.0,0.001,0.005,0.01],
    "model__max_depth" : [2,3,4,5,6,7,8,9,10],
    "model__min_samples_leaf": [5,10,20,30,40,50]
}

grid = GridSearchCV(
    pipe,
    param_grid,
    scoring="f1",
    cv=3,
    n_jobs=-1
)

In [15]:
grid.fit(x_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocess',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'PageValues', 'SpecialDay',
       'OperatingSystems', 'Browser', 'Region', 'TrafficType',
       'Product_Page_Duration'],
      dtype='object')),
                                                                        ('cat',
                                                                         OneHotEncoder(),
                                                                         Index(['Month', 'VisitorType'], dtype='object'))])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__ccp_alpha': [0.0, 0.001, 0.005, 0.01],
                         'model__max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'model__min_samples_leaf': [5, 10, 20, 30, 40, 50]},
             scoring='f1')

In [18]:
print("Best Parameters : ",grid.best_params_)
print("Best CV F1 : ",grid.best_score_)

y_pred = grid.predict(x_test)
print("Test F! : ",f1_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Best Parameters :  {'model__ccp_alpha': 0.0, 'model__max_depth': 5, 'model__min_samples_leaf': 30}
Best CV F1 :  0.6446911110260841
Test F! :  0.592375366568915
              precision    recall  f1-score   support

           0       0.90      0.97      0.93      2055
           1       0.75      0.49      0.59       411

    accuracy                           0.89      2466
   macro avg       0.83      0.73      0.76      2466
weighted avg       0.88      0.89      0.88      2466

[[1986   69]
 [ 209  202]]