In [1]:
import pandas as pd

In [2]:
d1 = pd.DataFrame(
    {
        'name' : ["Atiqa","Sadiqa","Saniya"],
        'id' : [1,3,3],
        'val' : ['a','b','c']
    }
)

d2 = pd.DataFrame(
    {
        'name' : ["Ali","Hun","Rose"],
        'id' : [1,2,2],
        'val' : ['f','e','d']
    }
)

print(d1)

print(d2)

     name  id val
0   Atiqa   1   a
1  Sadiqa   3   b
2  Saniya   3   c
   name  id val
0   Ali   1   f
1   Hun   2   e
2  Rose   2   d

In [6]:
# 1] Row-Wise :

pd.concat([d1,d2])

     name  id val
0   Atiqa   1   a
1  Sadiqa   3   b
2  Saniya   3   c
0     Ali   1   f
1     Hun   2   e
2    Rose   2   d

In [7]:
# 2] Col-Wise :

pd.concat([d1,d2],axis=1)

     name  id val  name  id val
0   Atiqa   1   a   Ali   1   f
1  Sadiqa   3   b   Hun   2   e
2  Saniya   3   c  Rose   2   d

In [8]:
# 3] Ignoring the previous idex :

pd.concat([d1,d2],ignore_index=True)

     name  id val
0   Atiqa   1   a
1  Sadiqa   3   b
2  Saniya   3   c
3     Ali   1   f
4     Hun   2   e
5    Rose   2   d