In [1]:
import pandas as pd

In [7]:
d1 = pd.DataFrame(
    {
        'name' : ["Atiqa","Sadiqa","Saniya"],
        'id' : [1,3,3],
        'val' : ['a','b','c']
    }
)

d2 = pd.DataFrame(
    {
        'name' : ["Ali","Hun","Rose"],
        'id' : [1,2,2],
        'val' : ['f','e','d']
    }
)

print(d1)

print(d2)

     name  id val
0   Atiqa   1   a
1  Sadiqa   3   b
2  Saniya   3   c
   name  id val
0   Ali   1   f
1   Hun   2   e
2  Rose   2   d

In [9]:
# 1] Inner Join :

pd.merge(d1,d2,on="id")

  name_x  id val_x name_y val_y
0  Atiqa   1     a    Ali     f

In [10]:
# 2] Outer Join :

pd.merge(d1,d2,on="id",how="outer")

   name_x  id val_x name_y val_y
0   Atiqa   1     a    Ali     f
1     NaN   2   NaN    Hun     e
2     NaN   2   NaN   Rose     d
3  Sadiqa   3     b    NaN   NaN
4  Saniya   3     c    NaN   NaN

In [11]:
# 3] Left Join ;

pd.merge(d1,d2,on="id",how="left")

   name_x  id val_x name_y val_y
0   Atiqa   1     a    Ali     f
1  Sadiqa   3     b    NaN   NaN
2  Saniya   3     c    NaN   NaN

In [12]:
# 3] Right Join ;

pd.merge(d1,d2,on="id",how="right")

  name_x  id val_x name_y val_y
0  Atiqa   1     a    Ali     f
1    NaN   2   NaN    Hun     e
2    NaN   2   NaN   Rose     d