In [1]:
import pandas as pd
d = pd.read_csv("raw_data.csv")

In [2]:
d

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
# 1] Melting : [Wide to long]

d = d.melt(
    id_vars = "name",
    value_vars = ["country","gender"],
    var_name = "Melted_Col_Heading",
    value_name = "Melted_Values"
)

In [4]:
d = d.drop_duplicates()
print(d)

            name Melted_Col_Heading Melted_Values
0       John Doe            country           USA
2     Jane Smith            country        Canada
3           Alex            country           USA
4   Maria Garcia            country         Spain
5         Li Wei            country         China
6            NaN            country         India
7     Ahmed Khan            country           NaN
8     Rachel Lee            country           USA
9    Carlos Ruiz            country        Mexico
10   Emily Davis            country           USA
11      John Doe             gender          Male
13    Jane Smith             gender        Female
14          Alex             gender       Unknown
15  Maria Garcia             gender        Female
16        Li Wei             gender          Male
17           NaN             gender        Female
18    Ahmed Khan             gender          Male
19    Rachel Lee             gender        Female
20   Carlos Ruiz             gender          Male
21   Emily Davis             gender           NaN

In [5]:
# 2] Pivot : [Long to Wide]

d = d.pivot(
    index = "name",
    columns = "Melted_Col_Heading",
    values = "Melted_Values"
)

In [6]:
d

Melted_Col_Heading country   gender
name
NaN                  India   Female
Ahmed Khan             NaN     Male
Alex                   USA  Unknown
Carlos Ruiz         Mexico     Male
Emily Davis            USA      NaN
Jane Smith          Canada   Female
John Doe               USA     Male
Li Wei               China     Male
Maria Garcia         Spain   Female
Rachel Lee             USA   Female