In [18]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import accuracy_score,precision_score,classification_report
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("employee_turnover.csv")

In [3]:
data.sample(10)

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
428,0.400672,0.404383,0.421528,0.702095,0.451913,0.260581,0.493117,0.945689,0.471167,0.139012,0.823451,0.917479,0.340490,0.678072,0.755499,1
432,0.820932,0.625996,0.064871,0.392211,0.806065,0.309268,0.965379,0.684042,0.724153,0.987447,0.763732,0.680971,0.641711,0.583287,0.520080,0
398,0.018923,0.395084,0.558794,0.167926,0.669815,0.961109,0.080918,0.009236,0.708262,0.793356,0.416277,0.345934,0.351635,0.173287,0.144004,0
845,0.102322,0.874587,0.727829,0.874430,0.390177,0.616341,0.479422,0.983199,0.389982,0.815603,0.589781,0.314641,0.411796,0.347842,0.185569,1
1037,0.899890,0.522163,0.618268,0.738553,0.032490,0.818738,0.053237,0.103341,0.098405,0.959777,0.531553,0.001293,0.915154,0.282548,0.000687,1
1093,0.674491,0.399414,0.673503,0.440394,0.278553,0.612995,0.091533,0.739238,0.862941,0.207237,0.248862,0.423371,0.364269,0.061932,0.105361,1
1114,0.165858,0.968011,0.211360,0.228528,0.225381,0.452278,0.892660,0.348990,0.177272,0.043333,0.889503,0.836168,0.174398,0.791215,0.743773,0
60,0.562442,0.361236,0.753637,0.758285,0.755041,0.790346,0.543473,0.820068,0.268484,0.914394,0.402036,0.530216,0.166245,0.161633,0.213166,1
214,0.836578,0.678419,0.711897,0.487429,0.604705,0.428114,0.567510,0.789791,0.199764,0.875896,0.306009,0.147567,0.634549,0.093642,0.045157,1
167,0.966802,0.882661,0.567481,0.886063,0.354918,0.200931,0.526045,0.531209,0.910072,0.005736,0.855551,0.608235,0.939644,0.731968,0.520377,1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB

In [5]:
data.describe()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
count,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1350.000000,1.350000e+03,1350.000000,1350.000000
mean,0.506386,0.487061,0.484761,0.499442,0.494884,0.509909,0.504329,0.500164,0.516149,0.506091,0.493360,0.486843,0.485767,3.291479e-01,0.240653,0.497778
std,0.291505,0.283808,0.282758,0.293013,0.289248,0.290110,0.295693,0.294835,0.295072,0.284901,0.292929,0.288342,0.285077,2.986314e-01,0.222281,0.500180
min,0.001738,0.000546,0.001545,0.000166,0.001319,0.005015,0.000424,0.000231,0.000150,0.000903,0.000491,0.001293,0.001595,2.410000e-07,0.000247,0.000000
25%,0.263051,0.238538,0.249651,0.246399,0.244162,0.263235,0.249894,0.239224,0.247978,0.269517,0.247274,0.233357,0.244944,6.114448e-02,0.058694,0.000000
50%,0.525340,0.468457,0.485414,0.495572,0.501617,0.532388,0.509448,0.499964,0.531408,0.504640,0.498490,0.475214,0.468982,2.484923e-01,0.165438,0.000000
75%,0.750987,0.724088,0.721622,0.753108,0.743938,0.761090,0.755113,0.767168,0.775888,0.761640,0.740231,0.747609,0.725870,5.479425e-01,0.367042,1.000000
max,0.998692,0.999957,0.999722,0.999931,0.997813,0.999143,0.999794,0.998365,0.999962,0.999964,0.998211,0.998330,0.999386,9.964245e-01,0.930338,1.000000

In [6]:
x = data.drop("Employee_Turnover",axis=1)
y = data["Employee_Turnover"]

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 42)

In [14]:
model = LogisticRegressionCV(
        l1_ratios=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0],
        random_state=43,
        solver='saga',
        cv=5,
        max_iter=1000
)
model.fit(x_train,y_train)

C:\Users\s...user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:2137: FutureWarning: The default value of the parameter 'scoring' will change from None, i.e. accuracy, to 'neg_log_loss' in version 1.11. To silence this warning, explicitly set the scoring parameter: scoring='neg_log_loss' for the new, scoring='accuracy' or scoring=None for the old default.
  warnings.warn(
C:\Users\s...user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:2150: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

LogisticRegressionCV(cv=5,
                     l1_ratios=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,
                                1.0],
                     max_iter=1000, random_state=43, solver='saga')

In [15]:
y_pred = model.predict(x_test)

In [16]:
# Accuracy Score :

print(f"Accuracy Score : {accuracy_score(y_test,y_pred)*100}%")
print(f"Accuracy Score : {precision_score(y_test,y_pred)*100}%")

Accuracy Score : 86.29629629629629%
Accuracy Score : 87.93103448275862%

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.90      0.88       145
           1       0.88      0.82      0.85       125

    accuracy                           0.86       270
   macro avg       0.86      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270