In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
df = datasets.load_iris(as_frame = True).frame

In [3]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [4]:
df.sample(3)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
3                  4.6               3.1                1.5               0.2       0
107                7.3               2.9                6.3               1.8       2
52                 6.9               3.1                4.9               1.5       1

In [5]:
X = df.drop("target",axis = 1)
y = df["target"]

In [6]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42, stratify = y
)

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled  = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [16]:
# Model Building :

svc = SVC()
svc.fit(x_train_scaled,y_train)

y_predict = svc.predict(x_test_scaled)

In [15]:
from sklearn.metrics import accuracy_score, classification_report

print("accuracy : ", accuracy_score(y_test,y_predict))
print("classification report : \n\n",classification_report(y_test,y_predict))

accuracy :  0.9333333333333333
classification report :

               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [19]:
# linear Kernel :

svc = SVC(kernel = 'linear')
svc.fit(x_train_scaled,y_train)

y_predict = svc.predict(x_test_scaled)

print("accuracy : ", accuracy_score(y_test,y_predict))

accuracy :  0.9111111111111111

In [21]:
# poly kernel :

svc = SVC(kernel = 'poly')
svc.fit(x_train_scaled,y_train)

y_predict = svc.predict(x_test_scaled)

print("accuracy : ", accuracy_score(y_test,y_predict))

accuracy :  0.8666666666666667

In [22]:
# sigmoid kernel :

svc = SVC(kernel = 'sigmoid')
svc.fit(x_train_scaled,y_train)

y_predict = svc.predict(x_test_scaled)

print("accuracy : ", accuracy_score(y_test,y_predict))

accuracy :  0.9111111111111111

In [24]:
# Hyperparameter :

c_vals = [0.5,1,2,3,4,5]

for c_val in c_vals:
    svc = SVC(kernel = 'rbf',C = c_val)
    svc.fit(x_train_scaled,y_train)
    
    y_predict = svc.predict(x_test_scaled)
    
    print("C : ",c_val," accuracy : ", accuracy_score(y_test,y_predict))

C :  0.5  accuracy :  0.9111111111111111
C :  1  accuracy :  0.9333333333333333
C :  2  accuracy :  0.9111111111111111
C :  3  accuracy :  0.9111111111111111
C :  4  accuracy :  0.9333333333333333
C :  5  accuracy :  0.9333333333333333